version: '3'

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
  - postgres
  - redis
  env_file: redash.env
  restart: always

services:
  postgres-airflow:
    image: postgres
    env_file: .env
    expose:
      - 5432
    volumes:
      - ./scripts_postgres:/docker-entrypoint-initdb.d

  postgres-dbt:
    image: postgres
    env_file: dbt.env
    expose:
      - 5432
    restart: always
    volumes:
      - ./data:/data

  mysqldb:
    image: mysql
    env_file: .env
    container_name: mysql_container_test
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    expose: 
      - 3306
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf  
      - ./data:/var/lib/mysql-files/

  airflow:
    build: .
    env_file: .env
    depends_on:
      - postgres-airflow
      - postgres-dbt
      - mysqldb
    ports:
      - 8000:8080
    volumes:
      - ./dbt:/dbt
      - ./data:/data
      - ./airflow:/airflow

  adminer:
    image: dockette/adminer:dg
    ports:
      - 8080:80
    depends_on:
      - postgres-airflow
      - postgres-dbt
      - postgres
      - mysqldb

  postgres:
    image: postgres
    env_file: redash.env
    restart: always

  server:
    <<: *redash-service
    command: server
    ports:
      - 5000:5000
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:latest
    restart: always

